//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YukiApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int id { get; set; }
        public int idSanPham { get; set; }
        public int idDonHang { get; set; }
        public decimal DonGia { get; set; }
        public int SoLuong { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
