//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucci_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPham
    {
        public int id { get; set; }
        public int idSanPham { get; set; }
        public string ThongTinSanPham { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
