//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucci_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int id { get; set; }
        public int idGioHang { get; set; }
        public string HoTen { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgayGio { get; set; }
        public string TrangThai { get; set; }
    
        public virtual GioHang GioHang { get; set; }
    }
}
